from gingerit.gingerit import GingerIt

def spell_checker(sentence):
	
	sentence = "a brief history of apache hadoop hadoop wa sstarted at yahool to provide a data processing infrastructure to the apache nutch web search engine the project wa sstarted by doug cutting and michael j cafarella in 2005 the name hadoop came from cutting given his toy elephant the name hadoops d a portion o fthe technica linspiration came from the google file system gfs and a 2004 google paper on the mapreduce algorithm yahool began embracing hadoop in 2006 and by 2008 the yahoo search index was being generated by hadoop one key design decision was to use lowcost commodity servers for both computing and storage indeed one of the important principles of early hadoop mapreduce process ing was the capability to move the computation to the datals becaus elt was faster than moving data from scrve rto server the design also required that hadoop software be scalable handle large amount sao fdata and tolerate hardwar efailures s the hadoo pdesign also sacrifices some efficiency 1n favor of massiv escalability at a small scale hadoop ma ypresen tan inefficient approach for some problems other tools may in fact provide better performanc e1n these cases as the problem or data set scales co massive proportions however hadoop begin sto sho wits ability to handle problem so fsizes that are impossible to manage on other systems some dreas where hadoo pis used include the following whos eson had e social media retail web commerce financial services web search government s research and development many others sa some prominen tusers include the following yahool facebook amazon ebay american airlines the new york times"
	print(len(sentence))

	if(len(sentence) > 500):
		corrected_sentence = ""
		i = 0
		j = 500
		while(j<=len(sentence)):
			parser = GingerIt()
			corrected_sentence += parser.parse(sentence[i:j])['result']
			i = j
			j = (j+500, len(sentence)) [j+500 <= len(sentence)]
	else:
		parser = GingerIt()
		corrected_sentence = parser.parse(sentence)['result']

	print("GingerIT():::\n", corrected_sentence)

	return corrected_sentence
spell_checker("")